version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - TOKEN=$TOKEN
      - NODE_OPTIONS="--max-old-space-size=8192"
    volumes:
      - .:/Users/richardbraman/IdeaProjects/bdt-bcda/
      - node_modules:/Users/richardbraman/IdeaProjects/bdt-bcda/node_modules
    command: ./node_modules/nodemon/bin/nodemon index.js --pattern "testSuite/**/!(authorization.test.js)"
volumes:
  node_modules:
